---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Change file ownership
  image: alpine:latest
  commands:
  - chown -R 1001:0 /drone/src

- name: Build project
  image: axarev/parsr
  environment:
    LD_LIBRARY_PATH: /opt/rh/rh-nodejs8/root/usr/lib64
    NODE_ENV: development
  commands:
  - export PATH=/opt/rh/rh-nodejs8/root/usr/bin:$PATH
  - npm install

- name: Run formatter
  image: axarev/parsr
  environment:
    LD_LIBRARY_PATH: /opt/rh/rh-nodejs8/root/usr/lib64
  commands:
  - export PATH=/opt/rh/rh-nodejs8/root/usr/bin:$PATH
  - npm run format

- name: Run linter
  image: node:8
  commands:
  - npm run lint

- name: Run tests
  image: axarev/parsr
  environment:
    LD_LIBRARY_PATH: /opt/rh/rh-nodejs8/root/usr/lib64
  commands:
  - export PATH=/opt/rh/rh-nodejs8/root/usr/bin:$PATH
  - npm run test

- name: Build Docker image
  image: plugins/docker
  settings:
    repo: axarev/parsr
    context: .
    dockerfile: docker/parsr/Dockerfile
    username: 
      from_secret: registry_user
    password: 
      from_secret: registry_password
    build_args:
      DEV_MODE: 'true'
  when:
    branch:
    - develop
    - feature/drone*
    event:
      exclude:
      - pull_request

